### ISSUE TITLE
porn list, missing: www.

### ISSUE THREAD

**Issue by surfskidude** [chadmayfield/pihole-blocklists#24] opened 2020-03-10 18:22 UTC
I use your list with Pi-hole and I noticed a lot of porn sites go through since one can also access them using www.xxxx.xx
Example: You block pornhub.com, but not www.pornhub.com.

**Comment by chadmayfield** [comment] 2020-03-10 18:28
Thank you for the feedback, this is a known issue (see issue #3 and #18), I have hopes to fix this issue sometime in the future (I am very busy at the moment).  Unfortunately this is very involved and big fix because sites can run on just about any subdomain, not just www.  When I get time I will be looking further into a possible fix akin to subdomain enumeration to better block all possible sites.

Closing as a duplicate of #18.

**Closed as completed by chadmayfield** 2020-03-10 18:28 UTC
Labels: duplicate
